#!/usr/bin/env node

import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const SCHEMA_URL =
  'https://developers.squarespace.com/commerce-apis/latest/schema-processor-version-version-latest.json';
const HTTP_METHODS = new Set(['get', 'post', 'put', 'patch', 'delete']);
const READ_ONLY_POSTS = new Set(['getTransactionsSummaries', 'queryContacts']);
const IDEMPOTENT_OPERATIONS = new Set(['adjustInventoryStockLevels', 'createOrder']);
const DESTRUCTIVE_OPERATIONS = new Set(['adjustInventoryStockLevels']);
const MAX_DESCRIPTION_LENGTH = 320;

const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const outputPath = resolve(scriptDirectory, '../src/generated/operations.ts');

const response = await fetch(SCHEMA_URL, {
  headers: { 'User-Agent': '@florasync/squarespace-mcp OpenAPI synchronizer' },
});
if (!response.ok) {
  throw new Error(`Unable to download Squarespace OpenAPI schema: HTTP ${response.status}`);
}

const document = await response.json();
const operations = [];

for (const [path, pathItem] of Object.entries(document.paths ?? {})) {
  for (const [method, rawOperation] of Object.entries(pathItem)) {
    if (!HTTP_METHODS.has(method) || typeof rawOperation !== 'object' || rawOperation === null) {
      continue;
    }

    const operation = rawOperation;
    const operationId = operation.operationId;
    if (typeof operationId !== 'string' || operationId.length === 0) {
      throw new Error(`Missing operationId for ${method.toUpperCase()} ${path}`);
    }

    const parameters = [...(pathItem.parameters ?? []), ...(operation.parameters ?? [])]
      .filter((parameter) => parameter?.in !== 'header' || !['Authorization', 'User-Agent'].includes(parameter.name))
      .map((parameter) => ({
        inputName: parameter.name === 'Idempotency-Key' ? 'idempotencyKey' : parameter.name,
        wireName: parameter.name,
        location: parameter.in,
        required: Boolean(parameter.required) && parameter.name !== 'Idempotency-Key',
        schema: compactSchema(resolveSchema(parameter.schema ?? {}, document)),
        description: truncate(parameter.description),
      }));

    if (
      IDEMPOTENT_OPERATIONS.has(operationId) &&
      !parameters.some((parameter) => parameter.inputName === 'idempotencyKey')
    ) {
      parameters.push({
        inputName: 'idempotencyKey',
        wireName: 'Idempotency-Key',
        location: 'header',
        required: false,
        schema: { type: 'string', maxLength: 64 },
        description: 'Optional retry key. A UUID is generated when omitted.',
      });
    }

    const requestContentType = selectRequestContentType(operation.requestBody?.content);
    const bodySchema = createBodySchema({ operationId, operation, requestContentType, document });
    const inputSchema = buildInputSchema(parameters, bodySchema, requestContentType);
    const readOnly = method === 'get' || READ_ONLY_POSTS.has(operationId);
    const destructive = method === 'delete' || DESTRUCTIVE_OPERATIONS.has(operationId);

    operations.push({
      name: `squarespace_${toSnakeCase(operationId)}`,
      operationId,
      title: operation.summary ?? operationId,
      description: buildDescription(operation, path, operationId),
      method: method.toUpperCase(),
      path,
      requestContentType,
      parameters,
      inputSchema,
      readOnly,
      destructive,
    });
  }
}

operations.sort((left, right) => left.name.localeCompare(right.name));

const generatedAt = new Date().toISOString();
const sourceVersion = String(document.info?.version ?? 'unknown');
const source = `// This file is generated by scripts/sync-openapi.mjs. Do not edit manually.
// Source: ${SCHEMA_URL}
// Synchronized: ${generatedAt}

import type { SquarespaceOperation } from '../operations/types.js';

export const SQUARESPACE_OPENAPI_SOURCE = ${JSON.stringify(SCHEMA_URL)};
export const SQUARESPACE_OPENAPI_VERSION = ${JSON.stringify(sourceVersion)};

export const SQUARESPACE_OPERATIONS = ${JSON.stringify(operations, null, 2)} as const satisfies readonly SquarespaceOperation[];
`;

await mkdir(dirname(outputPath), { recursive: true });
await writeFile(outputPath, source);
process.stdout.write(`Generated ${operations.length} Squarespace operations at ${outputPath}\n`);

function resolveSchema(schema, root, seen = new Set(), depth = 0) {
  if (!schema || typeof schema !== 'object') return {};
  if (depth > 24) return { type: 'object' };

  if (schema.$ref) {
    if (seen.has(schema.$ref)) return { type: 'object' };
    const nextSeen = new Set(seen).add(schema.$ref);
    return resolveSchema(resolvePointer(root, schema.$ref), root, nextSeen, depth + 1);
  }

  if (schema.readOnly === true) return undefined;

  const result = {};
  const allowedKeys = [
    'type',
    'title',
    'description',
    'format',
    'minimum',
    'maximum',
    'exclusiveMinimum',
    'exclusiveMaximum',
    'minLength',
    'maxLength',
    'pattern',
    'minItems',
    'maxItems',
    'uniqueItems',
    'enum',
    'const',
    'default',
  ];

  for (const key of allowedKeys) {
    if (schema[key] !== undefined) result[key] = schema[key];
  }
  if (result.description) result.description = truncate(result.description);

  for (const key of ['oneOf', 'anyOf', 'allOf']) {
    if (Array.isArray(schema[key])) {
      result[key] = schema[key].map((entry) => resolveSchema(entry, root, seen, depth + 1)).filter(Boolean);
    }
  }

  if (schema.items) {
    result.items = resolveSchema(schema.items, root, seen, depth + 1) ?? {};
  }

  if (schema.properties && typeof schema.properties === 'object') {
    const properties = {};
    for (const [name, property] of Object.entries(schema.properties)) {
      const resolved = resolveSchema(property, root, seen, depth + 1);
      if (resolved) properties[name] = resolved;
    }
    result.properties = properties;
    if (Array.isArray(schema.required)) {
      const required = schema.required.filter((name) => Object.hasOwn(properties, name));
      if (required.length > 0) result.required = required;
    }
  }

  if (schema.additionalProperties !== undefined) {
    result.additionalProperties =
      typeof schema.additionalProperties === 'object'
        ? resolveSchema(schema.additionalProperties, root, seen, depth + 1)
        : schema.additionalProperties;
  }

  if (schema.nullable === true) {
    if (typeof result.type === 'string') result.type = [result.type, 'null'];
    else result.anyOf = [...(result.anyOf ?? []), { type: 'null' }];
  }

  return result;
}

function compactSchema(schema) {
  if (!schema || typeof schema !== 'object') return {};
  const result = Array.isArray(schema) ? [] : {};
  for (const [key, value] of Object.entries(schema)) {
    if (key === 'default' || key === 'title') continue;
    result[key] = value && typeof value === 'object' ? compactSchema(value) : value;
  }
  return result;
}

function resolvePointer(root, pointer) {
  if (!pointer.startsWith('#/')) throw new Error(`Unsupported external schema reference: ${pointer}`);
  return pointer
    .slice(2)
    .split('/')
    .map((part) => part.replaceAll('~1', '/').replaceAll('~0', '~'))
    .reduce((value, part) => value?.[part], root);
}

function selectRequestContentType(content) {
  if (!content) return undefined;
  const supported = ['application/json', 'application/merge-patch+json', 'multipart/form-data'];
  return supported.find((contentType) => Object.hasOwn(content, contentType));
}

function createBodySchema({ operationId, operation, requestContentType, document: root }) {
  if (!requestContentType) return undefined;
  if (requestContentType === 'multipart/form-data' && operationId === 'uploadProductImage') {
    return {
      type: 'object',
      properties: {
        imageBase64: {
          type: 'string',
          description: 'Base64-encoded image bytes. Do not include a data URL prefix.',
        },
        filename: { type: 'string', description: 'Image filename including its extension.' },
        contentType: {
          type: 'string',
          description: 'Image media type, for example image/jpeg or image/png.',
        },
      },
      required: ['imageBase64', 'filename', 'contentType'],
      additionalProperties: false,
    };
  }

  const mediaType = operation.requestBody?.content?.[requestContentType];
  return compactSchema(resolveSchema(mediaType?.schema ?? { type: 'object' }, root));
}

function buildInputSchema(parameters, bodySchema, requestContentType) {
  const properties = {};
  const required = [];
  for (const parameter of parameters) {
    properties[parameter.inputName] = {
      ...parameter.schema,
      ...(parameter.description ? { description: parameter.description } : {}),
    };
    if (parameter.required) required.push(parameter.inputName);
  }

  if (bodySchema) {
    if (requestContentType === 'multipart/form-data') {
      Object.assign(properties, bodySchema.properties);
      required.push(...(bodySchema.required ?? []));
    } else {
      properties.body = bodySchema;
      required.push('body');
    }
  }

  return {
    type: 'object',
    properties,
    ...(required.length > 0 ? { required: [...new Set(required)] } : {}),
    additionalProperties: false,
  };
}

function buildDescription(operation, path, operationId) {
  const parts = [operation.summary, operation.description].filter(Boolean);
  if (operationId === 'getProfiles' || operationId === 'getSpecificProfiles') {
    parts.push('Profiles is in maintenance mode; prefer the Contacts tools for new integrations.');
  }
  if (path.startsWith('/1.0/webhook_subscriptions')) {
    parts.push('Squarespace requires an OAuth access token for webhook subscription operations.');
  }
  return truncate(parts.join(' '));
}

function toSnakeCase(value) {
  return value
    .replace(/([a-z0-9])([A-Z])/g, '$1_$2')
    .replace(/[^a-zA-Z0-9]+/g, '_')
    .toLowerCase();
}

function truncate(value) {
  if (typeof value !== 'string') return undefined;
  const normalized = value.replace(/\s+/g, ' ').trim();
  return normalized.length <= MAX_DESCRIPTION_LENGTH
    ? normalized
    : `${normalized.slice(0, MAX_DESCRIPTION_LENGTH - 1)}…`;
}
